---
# PodDisruptionBudget for high availability
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mcp-server-pdb
  namespace: mcp-server
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: mcp-server
